services:
  # PostgreSQL: banco de dados
  database:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: accenture_test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Java Spring Boot: backend
  backend:
    build: ./backend
    container_name: backend_java
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/accenture_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - database
    restart: on-failure

  # Vue + Nginx: frontend
  frontend:
    build: ./frontend
    container_name: frontend_vue
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  postgres-data: # Volume para manter estado do banco de dados